# Generated by Django 3.2.12 on 2022-02-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_globalcontact_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcontact',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
